export enum GameType {
  EMOVI = "EMOVI",
  FRAMED = "FRAMED",
  WORDLE = "WORDLE",
  WHERE_TAKEN = "WHERE_TAKEN",
  CONNECTIONS = "CONNECTIONS",
  STRANDS = "STRANDS",
  MINI_CROSSWORD = "MINI_CROSSWORD",
  TRAVLE_USA = "TRAVLE_USA",
  BANDLE = "BANDLE",
  JUMBLIE = "JUMBLIE",
  ENSPELLED = "ENSPELLED",
  UNKNOWN = "UNKNOWN",
}
