export enum GameType {
  EMOVIE = "EMOVIE",
  FRAMED = "FRAMED",
  WORDLE = "WORDLE",
  WHERE_TAKEN = "WHERE_TAKEN",
  CONNECTIONS = "CONNECTIONS",
  STRANDS = "STRANDS",
  MINI_CROSSWORD = "MINI_CROSSWORD",
}
